### PR TITLE
Workflows

### PR DESCRIPTION
**Pull request by Edoardo-Pedicillo**
This PR deploy the workflows

### CODE REVIEW

**Comment by Edoardo-Pedicillo** [comment]
This PR is ready, but the linting is failing. @MatteoRobbiati could you please fix it?

**Comment by Edoardo-Pedicillo** [comment]
I removed the `pdbpp` dependency, because it is not strictly related to tests  and it cause the following error
https://github.com/qibogang/qiboml/actions/runs/8360680848/job/22887073306#step:11:49, it seems one of its dependency `py3k_compat` is not updated with py 3.10 changes related to `Callable` (see https://stackoverflow.com/questions/69515086/error-attributeerror-collections-has-no-attribute-callable-using-beautifu)

**Comment by Edoardo-Pedicillo** [comment]
After speaking with @alecandido, we agree it is better to take the `pdbpp` dependency and set the dependencies of the `dev` group optional.

**Comment by MatteoRobbiati** [comment]
> After speaking with @alecandido, we agree it is better to take the `pdbpp` dependency and set the dependencies of the `dev` group optional.

Fine with me.

**Comment by Edoardo-Pedicillo** [comment]
@MatteoRobbiati this PR is ready, let me know how many approvals I need.

**Pull request merged**
